/run/initialize

/vis/open OGL 600x600-0+0
/vis/drawVolume
/vis/scene/add/trajectories
/vis/viewer/set/upVector 0 0 1
/vis/viewer/set/viewpointVector .7 -.7 .2
/vis/viewer/zoom 2

/vis/viewer/set/style surface
/vis/modeling/trajectories/create/drawByCharge
/vis/scene/add/axes 0 0 0 1 m
/vis/scene/endOfEventAction accumulate 10

# /control/execute gps.mac
/control/execute cry.mac

/tracking/verbose 0

/run/printProgress 100
/run/verbose 0
/run/beamOn 10
