/run/initialize

/vis/open OGL 600x600-0+0
/vis/drawVolume
/vis/scene/add/trajectories
/vis/viewer/set/upVector 0 0 1
/vis/viewer/set/viewpointVector .7 -.7 .2
/vis/viewer/zoom 2

/vis/viewer/set/style surface
/vis/modeling/trajectories/create/drawByCharge
/vis/scene/add/axes 0 0 0 1 m

/gps/verbose 0
/gps/source/intensity 1.
# /gps/particle neutron
/gps/particle gamma
/gps/position 458.90 0 -1280.8 mm
/gps/direction 1 0 0
/gps/ang/type cos
/gps/pos/type Plane
/gps/pos/shape Square
/gps/pos/halfy .5 m
/gps/pos/halfz .5 m
/gps/pos/centre -196.850 0 -1280.8 mm

/gps/ene/type User
/gps/hist/type energy
/control/execute Watt_neutron_pdf.gdat
/run/printProgress 100
/run/verbose 0
/run/beamOn 2
